[package]
name = "flashlog"
version = "1.0.0"
edition = "2021"
authors = ["Junbeom Lee <junbeoml22@gmail.com>"]
description = "A fast logging library for Rust"
license = "MIT OR Apache-2.0"
repository = "https://https://github.com/JunbeomL22/flashlog"

[profile.release]
opt-level = 3

members = [
    "flashlog",
    "example",
]
