[package]
name = "example-log"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
flashlog = { version = "1.0", path = "../../" }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }